name: Ruby

on:
  push:
    branches:
      - main
      - develop
    tags:
      - '*'

  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.3.6'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: bundle exec rake

  build:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.3.6'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Sign-in to RubyGems.org
      run: gem signin --api-key ${{ secrets.API_KEY }}
    - name: Build gem
      run: gem build imap_mogura.gemspec
    - name: Publish gem
      run: gem push imap_mogura-0.1.0.gem
