name: Ruby

on:
  push:
    branches:
      - main
      - develop
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.3.6'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: bundle exec rake

  build:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: test
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.3.6'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Build gem
      run: gem build imap_mogura.gemspec

    - name: Get tag name
      id: get_tag_name
      run: echo "::set-output name=TAG_NAME::${GITHUB_REF#refs/tags/}"

    - name: Publish gem
      run: GEM_HOST_API_KEY=${{ secrets.API_KEY }} gem push imap_mogura-${{ steps.get_tag_name.outputs.TAG_NAME }}.gem
